#SPDX-License-Identifier: MIT-0
---
- name: update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "debian"

- name: enable service
  ansible.builtin.systemd_service:
    service: tor
    state: started
    enabled: true

- name: restart service
  ansible.builtin.systemd_service:
    service: tor
    state: restarted
...

