---
- name: install iptables-persistent
  ansible.builtin.apt:
    pkg:
      - iptables-persistent
    update_cache: yes
    state: present
  become: true

- name: Allow lo interface
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: eth0
  become: true


- name: Allow new incoming SYN packets on TCP port 22 (SSH)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections
  become: true
    

- name: Allow icmp (ping)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
  become: true


- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true


- name: Allow HTTP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Allow HTTP and HTTPS
  become: true

- name: Allow HTTPS
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    ctstate: NEW
    jump: ACCEPT
    comment: Allow HTTPS
  become: true


- name: iptables -P INPUT DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
  become: true

