#SPDX-License-Identifier: MIT-0
---
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: enable service
  ansible.builtin.systemd_service:
    service: tinyproxy
    state: started

- name: restart service
  ansible.builtin.systemd_service:
    service: tinyproxy
    state: restarted

